/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-05 07:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class faculty_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("    <html class=\"no-js\" lang=\"zxx\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Virtual Classroom</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("\n");
      out.write("        <!-- CSS here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        ");

		if(session.getAttribute("faculty") == null)									// check if faculty is already logged in to the system
		{
			response.sendRedirect("faculty_login.jsp");								// if not logged in, take faculty to login page
		}

      out.write("\n");
      out.write("\n");
      out.write("            <!-- ? Preloader Start -->\n");
      out.write("            <div id=\"preloader-active\">\n");
      out.write("                <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("                    <div class=\"preloader-inner position-relative\">\n");
      out.write("                        <div class=\"preloader-circle\"></div>\n");
      out.write("                        <div class=\"preloader-img pere-text\">\n");
      out.write("                            <img src=\"assets/img/logo/loder.png\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Preloader Start -->\n");
      out.write("            <header>\n");
      out.write("                <!-- Header Start -->\n");
      out.write("                <div class=\"header-area header-transparent\">\n");
      out.write("                    <div class=\"main-header \">\n");
      out.write("                        <div class=\"header-bottom  header-sticky\">\n");
      out.write("                            <div class=\"container-fluid\">\n");
      out.write("                                <div class=\"row align-items-center\">\n");
      out.write("                                    <!-- Logo -->\n");
      out.write("                                    <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                                        <div class=\"logo\">\n");
      out.write("                                            <a href=\"index.jsp\"><img src=\"assets/img/logo/logo.png\" alt=\"\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                                        <div class=\"menu-wrapper d-flex align-items-center justify-content-end\">\n");
      out.write("                                            <!-- Main-menu -->\n");
      out.write("                                            <div class=\"main-menu d-none d-lg-block\">\n");
      out.write("                                                <nav>\n");
      out.write("                                                    <ul id=\"navigation\">\n");
      out.write("                                                        <li class=\"active\"><a href=\"faculty_dashboard.jsp\">Home</a></li>\n");
      out.write("                                                        <li><a href=\"#\">Classroom</a>\n");
      out.write("                                                            <ul class=\"submenu\">\n");
      out.write("                                                                <li><a href=\"\">Video Lectures</a></li>\n");
      out.write("                                                                <li><a href=\"\">Study Materials</a></li>\n");
      out.write("                                                            </ul>\n");
      out.write("                                                        </li>\n");
      out.write("                                                        <li><a href=\"\">Q/A Forum</a></li>\n");
      out.write("                                                        <!-- Button -->\n");
      out.write("                                                        <li class=\"button-header\"><a href=\"faculty_logout.jsp\" class=\"btn btn3\">Log Out</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </nav>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Mobile Menu -->\n");
      out.write("                                    <div class=\"col-12\">\n");
      out.write("                                        <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Header End -->\n");
      out.write("            </header>\n");
      out.write("            <main>\n");
      out.write("                <!--? slider Area Start-->\n");
      out.write("                <section class=\"slider-area \">\n");
      out.write("                    <div class=\"slider-active\">\n");
      out.write("                        <!-- Single Slider -->\n");
      out.write("                        <div class=\"single-slider slider-height d-flex align-items-center\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-xl-6 col-lg-7 col-md-12\">\n");
      out.write("                                        <div class=\"hero__caption\">\n");
      out.write("                                            <h1 data-animation=\"fadeInLeft\" data-delay=\"0.2s\">Welcome<br>\n");
      out.write("                                                ");
 out.println(session.getAttribute("faculty")); 
      out.write("\n");
      out.write("                                            </h1>\n");
      out.write("                                            <p data-animation=\"fadeInLeft\" data-delay=\"0.4s\">Attend video lectures, skim through study materials and ask doubts at one place.</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            </main>\n");
      out.write("            <footer>\n");
      out.write("                <div class=\"footer-wrappper footer-bg\">\n");
      out.write("                    <!-- Footer Start-->\n");
      out.write("                    <div class=\"footer-area footer-padding\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-between\">\n");
      out.write("                                <div class=\"col-xl-4 col-lg-5 col-md-4 col-sm-6\">\n");
      out.write("                                    <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                        <div class=\"single-footer-caption mb-30\">\n");
      out.write("                                            <!-- logo -->\n");
      out.write("                                            <div class=\"footer-logo mb-25\">\n");
      out.write("                                                <a href=\"index.jsp\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"footer-tittle\">\n");
      out.write("                                                <div class=\"footer-pera\">\n");
      out.write("                                                    <p>The automated process starts here.</p>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- footer-bottom area -->\n");
      out.write("                                <div class=\"footer-bottom-area\">\n");
      out.write("                                    <div class=\"container\">\n");
      out.write("                                        <div class=\"footer-border\">\n");
      out.write("                                            <div class=\"row d-flex align-items-center\">\n");
      out.write("                                                <div class=\"col-xl-12 \">\n");
      out.write("                                                    <div class=\"footer-copy-right text-center\">\n");
      out.write("                                                        <p>\n");
      out.write("                                                            Copyright &copy;\n");
      out.write("                                                            <script>\n");
      out.write("                                                                document.write(new Date().getFullYear());\n");
      out.write("                                                            </script> All rights reserved\n");
      out.write("                                                        </p>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Footer End-->\n");
      out.write("                            </div>\n");
      out.write("            </footer>\n");
      out.write("            <!-- Scroll Up -->\n");
      out.write("            <div id=\"back-top\">\n");
      out.write("                <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- JS here -->\n");
      out.write("            <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("            <!-- Jquery, Popper, Bootstrap -->\n");
      out.write("            <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("            <!-- Jquery Mobile Menu -->\n");
      out.write("            <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("            <!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("            <script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("            <!-- One Page, Animated-HeadLin -->\n");
      out.write("            <script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("\n");
      out.write("            <!-- Date Picker -->\n");
      out.write("            <script src=\"./assets/js/gijgo.min.js\"></script>\n");
      out.write("            <!-- Nice-select, sticky -->\n");
      out.write("            <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.sticky.js\"></script>\n");
      out.write("            <!-- Progress -->\n");
      out.write("            <script src=\"./assets/js/jquery.barfiller.js\"></script>\n");
      out.write("\n");
      out.write("            <!-- counter , waypoint,Hover Direction -->\n");
      out.write("            <script src=\"./assets/js/jquery.counterup.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/waypoints.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.countdown.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\n");
      out.write("\n");
      out.write("            <!-- contact js -->\n");
      out.write("            <script src=\"./assets/js/contact.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("            <script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("            <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\n");
      out.write("            <!-- Jquery Plugins, main Jquery -->\n");
      out.write("            <script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("            <script src=\"./assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
