/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-05 06:53:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class student_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


/**
 * Centralized DB configuration for all JSP pages.
 *
 * Override defaults using environment variables:
 * - DB_URL (e.g. jdbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=UTC)
 * - DB_USER
 * - DB_PASSWORD
 */
public static class Db {
  private static volatile boolean driverLoaded = false;

  private static void ensureDriver() throws ClassNotFoundException {
    if (!driverLoaded) {
      synchronized (Db.class) {
        if (!driverLoaded) {
          Class.forName("com.mysql.cj.jdbc.Driver");
          driverLoaded = true;
        }
      }
    }
  }

  public static Connection getConnection() throws Exception {
    ensureDriver();

    String url = System.getenv("DB_URL");
    if (url == null || url.trim().isEmpty()) {
      url = "jdbc:mysql://localhost:3306/project";
    }

    String user = System.getenv("DB_USER");
    if (user == null || user.trim().isEmpty()) {
      user = "root";
    }

    String password = System.getenv("DB_PASSWORD");
    if (password == null) {
      password = "Mypasswordis2425";
    }

    return DriverManager.getConnection(url, user, password);
  }
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/db.jspf", Long.valueOf(1770274385139L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("    <html class=\"no-js\" lang=\"zxx\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Student Login</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("\n");
      out.write("        <!-- CSS here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!-- ? Preloader Start -->\n");
      out.write("        <div id=\"preloader-active\">\n");
      out.write("            <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("                <div class=\"preloader-inner position-relative\">\n");
      out.write("                    <div class=\"preloader-circle\"></div>\n");
      out.write("                    <div class=\"preloader-img pere-text\">\n");
      out.write("                        <img src=\"assets/img/logo/loder.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Preloader Start-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <main class=\"login-body\">\n");
      out.write("            <!-- Login Student -->\n");
      out.write("            <form class=\"form-default\" name=\"myform\" action=\"student_login.jsp\" method=\"POST\">\n");
      out.write("\n");
      out.write("                ");

		// if student is already logged in to the system, redirect to the dashboard
		if(session.getAttribute("student") != null)
		{
			response.sendRedirect("student_dashboard.jsp");
		}

      out.write("\n");
      out.write("                    <div class=\"login-form\">\n");
      out.write("                        <!-- logo-login -->\n");
      out.write("                        <div class=\"logo-login\">\n");
      out.write("                            <a href=\"index.jsp\"><img src=\"assets/img/logo/loder.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <h2>Login Here</h2>\n");
      out.write("                        <div class=\"form-input\">\n");
      out.write("                            <input type=\"text\" name=\"roll_no\" placeholder=\"Roll No\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-input\">\n");
      out.write("                            <input type=\"password\" name=\"password\" placeholder=\"Password\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <p style=\"color:red\">\n");
      out.write("                            ");

		if(session.getAttribute("Error") != null)
		{
			out.println(session.getAttribute("Error"));
		}
/*		if(session.getAttribute("StudentErrorLogin") != null)
		{
			out.println(session.getAttribute("StudentErrorLogin"));
		}
		if(session.getAttribute("Rejected") != null)
		{
			out.println(session.getAttribute("Rejected"));
		}
*/

      out.write("\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"form-input pt-30\">\n");
      out.write("                            <input type=\"submit\" name=\"submit\" value=\"login\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Forgot Password -->\n");
      out.write("                        <a href=\"#\" class=\"forget\">Forgot Password</a>\n");
      out.write("                        <!-- Forgot Password -->\n");
      out.write("                        <a href=\"student_register.jsp\" class=\"registration\"> You dont't have an account? <b> Register here </b> </a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");

	// getting all required fields of login of student for validation
	String no = request.getParameter("roll_no");
	String password = request.getParameter("password");

	try
	{
		// establish the connection
		Connection con = Db.getConnection();

		// create a SQL statement
		Statement stmt = con.createStatement();
		String sql = "select * from student where roll_no = " + no + " and password = SHA1 ('" + password + "')";

		// execute the SQL statement
		ResultSet rs = stmt.executeQuery (sql);

		// if details found in database 
		if(rs.next())
		{
			// if request is not yet accepted by Admin
			if(rs.getInt("is_approved") == 0)
			{
				session.removeAttribute("Error");
				session.setAttribute("Error","Your Request is not yet accepted by Administrator");
			}
			// if request is accepted by Admin
			else if(rs.getInt("is_approved") == 1)
			{
				session.setAttribute("student",rs.getString(2));
				response.sendRedirect("student_dashboard.jsp");
			}
		}

		// if details not found in database
		else
		{
			// create a SQL statement
			String sql1 = "select * from student where roll_no = " + no;

			// execute a SQL statement
			ResultSet rs1 = stmt.executeQuery (sql1);

			// if details are incorrect, display error message
			if(rs1.next())
			{
				session.removeAttribute("Error");
				session.setAttribute("Error","Invalid Roll Number / Password");
			}
			// if request is rejected, go to home page
			else
			{
				session.removeAttribute("Error");
				session.setAttribute("Error","Your request is rejected by Administrator");
			}
		}

		// close the connection
		con.close();
	}
	catch(Exception e)
	{
		out.println(e);
	}

      out.write("\n");
      out.write("            </form>\n");
      out.write("            <!-- /end login form -->\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("        <!-- Jquery, Popper, Bootstrap -->\n");
      out.write("        <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("        <!-- Jquery Mobile Menu -->\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Video bg -->\n");
      out.write("        <script src=\"./assets/js/jquery.vide.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("        <!-- One Page, Animated-HeadLin -->\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Date Picker -->\n");
      out.write("        <script src=\"./assets/js/gijgo.min.js\"></script>\n");
      out.write("        <!-- Nice-select, sticky -->\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.sticky.js\"></script>\n");
      out.write("        <!-- Progress -->\n");
      out.write("        <script src=\"./assets/js/jquery.barfiller.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- counter , waypoint,Hover Direction -->\n");
      out.write("        <script src=\"./assets/js/jquery.counterup.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/waypoints.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.countdown.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- contact js -->\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Jquery Plugins, main Jquery -->\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
